### ISSUE TITLE
it don;t work?????

### ISSUE THREAD

**Issue by deadvcr** [Rhodesia/javaAP#1]
help how to make work again?????

i press button and type java but it doesnt go!!!!

pls make better coder.

-pajeet

**Comment by Rhodesia** [comment]
this project is old as fuck, idk how to make a makefile for java but if you want to try out any of the programs, cd into the folder and use javac to compile.

**Comment by Rhodesia** [comment]
commit #55e8fd02c771ed002fdf78d5b392148aa9f29a8e adds a buildfile, ill check if it works in a sec (im not on a box with java atm)

**Comment by Rhodesia** [comment]
InChains refuses to compile on my machine, but the buildscript works and everything is alright. InChains was an incomplete project to begin with LOL
